"""Case converter stubs."""

def kebabcase(value: str) -> str: ...
def snakecase(value: str) -> str: ...
def camelcase(value: str) -> str: ...
def pascalcase(value: str) -> str: ...
def spinalcase(value: str) -> str: ...
def constantcase(value: str) -> str: ...
def capitalcase(value: str) -> str: ...
def titlecase(value: str) -> str: ...
def dotcase(value: str) -> str: ...
def pathcase(value: str) -> str: ...
def headercase(value: str) -> str: ...
